export const cartActionTypes = {
    TOGGLE_CART_STATE: 'TOGGLE_CART_STATE',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_CARD_ITEM_FROM_CART: 'REMOVE_CARD_ITEM_FROM_CART',
    REMOVE_CART_ITEM:'REMOVE_CART_ITEM',
    CLEAR_CART:'CLEAR_CART'
}