const UserTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    EMAIL_PASSWORD_SIGN_IN_START: 'EMAIL_PASSWORD_SIGN_IN_START',
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    SIGN_OUT_USER_START:'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS:'SIGN_OUT_USER_SUCCESS',
    SIGN_OUT_USER_FAILURE:'SIGN_OUT_USER_FAILURE',
    SING_UP_START:'SING_UP_START',
    SING_UP_SUCCESS:'SING_UP_SUCCESS',
    SING_UP_FAILURE:'SING_UP_FAILURE',
}

export default UserTypes;